ERP-SPARTAN/Controllers/AlertController.cs
using BusinesLogic.UnitOfWork;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.Enums;
using Models.Models.Shared;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ERP_SPARTAN.Controllers
{
    [Authorize]
    public class AlertController : BaseController
    {
        private readonly IUnitOfWork _services;
        public AlertController(IUnitOfWork service) => _services = service;

        [Authorize(Roles = nameof(RolsAuthorization.Admin))]
        [HttpGet]
        public async Task<IActionResult> Index()
            => View(await _services.AlertService.GetAllWithRelationShips());

        [HttpGet]
        public async Task<IActionResult> MyAlerts()
        {
            var result = _services.AlertService.Filter(x => x.UserId == GetUserLoggedId());
            return View(await result.OrderByDescending(x => x.CreateAt).ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Clients = await _services.ClientUserService.GetListItem(x => x.CreatedBy == GetUserLoggedId());
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Quantity() => Ok(await _services.AlertService.Quantity(GetUserLoggedId()));

        [HttpPost]
        public async Task<IActionResult> Create(Alert model)
        {
            if (!ModelState.IsValid) return View(model);
            var result = false;
            if (model.IsMasive) result = await _services.AlertService.SendMasive(model, GetUserLoggedId());
            else result = await _services.AlertService.Add(model);
            if (!result)
            {
                BasicNotification("Intente de nuevo", NotificationType.error, "Error");
                return View(model);
            }
            BasicNotification("Alerta Enviada", NotificationType.success, "Exito");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> MaskAsRead()
        {
            var result = await _services.AlertService.MaskAsRead(GetUserLoggedId());
            if (!result)
            {
                BasicNotification("Error intente de nuevo", NotificationType.error);
            }
            return RedirectToAction(nameof(MyAlerts));
        }

        [HttpPost]
        public async Task<IActionResult> Remove(Guid id)
        {
            var alert = await _services.AlertService.GetById(id);
            if (alert == null) return NotFound();
            if (await _services.AlertService.Remove(alert)) return Ok(true);
            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> Remove()
        {
            var result = await _services.AlertService.RemoveAll();
            if (!result) BasicNotification("Error intente de nuevo", NotificationType.error);
            BasicNotification("Acción realizada correctamente", NotificationType.success);
            return RedirectToAction(nameof(Index));
        }
    }
}

ERP-SPARTAN/Controllers/InventaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BusinesLogic.UnitOfWork;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Enums;
using Models.Models;

namespace ERP_SPARTAN.Controllers
{
    [Authorize(Roles = nameof(RolsAuthorization.HiInventory))]
    public class InventaryController : BaseController
    {
        private readonly IUnitOfWork _service;
        public InventaryController(IUnitOfWork service) => _service = service;
        public async Task<IActionResult> Index()
        {
            var user = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            return View(await _service.InventaryService.GetByIdAll(user));
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Article model)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            model.UserId = userId;
            if (ModelState.IsValid)
            {
                if (await _service.InventaryService.Add(model))
                {
                    BasicNotification("Articulo agregado", NotificationType.success);
                    return RedirectToAction(nameof(Index));
                }
                BasicNotification("Ocurrio un error intente de nuevo", NotificationType.error);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var model = await _service.InventaryService.GetById(id);
            if (model != null) return View(model);
            return new NotFoundView();
        }

        [HttpPost]
        public async Task<IActionResult> Update(Article model)
        {
            model.UpdateAt = DateTime.Now;
            if (ModelState.IsValid)
            {
                if(await _service.InventaryService.Update(model))
                {
                    BasicNotification("Articulo Actualizado", NotificationType.success);
                    return RedirectToAction(nameof(Index));
                }
                BasicNotification("Ocurrio un error intente de nuevo", NotificationType.error);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(Guid id)
        {
            var article = await _service.InventaryService.GetById(id);
            if (article == null) return NotFound();
            if (await _service.InventaryService.Remove(article)) return Ok(true);
            return BadRequest();
        }
    }
}

ERP-SPARTAN/Controllers/LoanController.cs
using BusinesLogic.UnitOfWork;
using Commons.Extensions;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.Enums;
using Models.Enums.HiAccounting;
using Models.Models.HiAccounting;
using Models.ViewModels.HiLoans.Loans;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ERP_SPARTAN.Controllers
{
    [Authorize(Roles = nameof(RolsAuthorization.HILoans))]
    public class LoanController : BaseController
    {
        private readonly IUnitOfWork _service;
        public LoanController(IUnitOfWork unitOfWork) => _service = unitOfWork;

        [HttpGet]
        public async Task<IActionResult> Index(Guid? idEnterprise = null)
        {
            var userId = GetUserLoggedId();
            ViewBag.Enterprises = await _service.EnterpriseService.GetListItem(x => x.UserId == userId);
            return View(await _service.LoanService.GetAllWithRelationShip(userId, idEnterprise));
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var result = await _service.ClientUserService.GetAllWithRelationships(GetUserLoggedId(), null);
            ViewBag.Clients = result.Select(x => new SelectListItem
            {
                Text = x.User.FullName,
                Value = x.Id.ToString(),
                Group = new SelectListGroup { Name = x.Enterprise.Name }
            });
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Loan model , string contractDate = null)
        {
            //for change the contract day
            if (!string.IsNullOrEmpty(contractDate)) model.CreateAt = contractDate.ToDateTime();

            model.UserId = GetUserLoggedId();
            var clients = await _service.ClientUserService.GetAllWithRelationships(GetUserLoggedId(), null);
            ViewBag.Clients = clients.Select(x => new SelectListItem
            {
                Text = x.User.FullName,
                Value = x.Id.ToString(),
                Group = new SelectListGroup { Name = x.Enterprise.Name }
            });



            if (!ModelState.IsValid) return View(model);

            if (model.AmortitationType == AmortitationType.Open_o_Personalfee)
            {
                model.Shares = 1;
            }
            if (model.Shares <= 0 || model.AmountDeb <= 0 || model.InitialCapital <= 0)
            {
                BasicNotification("Lo sentimos, hay campos en el formulario que deben ser mayor a cero", NotificationType.error);
                return View(model);
            }
            if (model.AmortitationType == AmortitationType.Open_o_Personalfee)
            {
                model.Shares = _service.LoanService.getShares(model);
            }

            var result = await _service.LoanService.Add(model);
            if (!result)
            {
                BasicNotification("Lo sentimos, Intente de nuevo", NotificationType.error);
                return View(model);
            }
            BasicNotification("Agregado correctamente", NotificationType.success);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> GetById(Guid id, State stateDeb = State.All)
        {
            ViewBag.Selected = stateDeb;
            ViewBag.Action = nameof(GetById);
            ViewBag.AccessUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/{nameof(Loan)}/{nameof(GetMyLoan)}";
            var result = await _service.LoanService.GetByIdWithRelationships(id, stateDeb);
            if (result == null) new NotFoundView();
            return View(result);
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetMyLoan(Guid id, State stateDeb = State.All, Guid? reclosingId = null)
        {
            ViewBag.Selected = stateDeb;
            ViewBag.Action = nameof(GetMyLoan);
            ViewBag.ReclosingId = reclosingId;
            var result = await _service.LoanService.GetByIdWithRelationships(id, stateDeb);
            if (result == null) new NotFoundView();
            return View(nameof(GetById), result);
        }


        [HttpPost]
        public async Task<IActionResult> Remove(Guid id)
        {
            var result = await _service.LoanService.SoftRemove(id);
            if (!result) return BadRequest();
            return Ok(result);
        }

        [HttpPost]
        public async Task<IActionResult> PaymentDeb(PaymentLoanVM model)
        {
            var total = Math.Abs(model.AmortizationTotal - model.Amortization);
            if (model.ExtraMount > total)
            {
                BasicNotification("El monto a abonar es mayor que el capital actual, intente abonar un monto menor", NotificationType.warning, "Error");
                return RedirectToAction(nameof(GetById), new { id = model.IdLoan });
            }
            var result = await _service.LoanService.PaymentDeb(model.IdDeb, model.IdLoan, model.ExtraMount, model.InterestOnly);
            if (!result) BasicNotification("Error intente de nuevo", NotificationType.error);
            BasicNotification("Acción Realizada", NotificationType.success);
            return RedirectToAction(nameof(GetById), new { id = model.IdLoan });
        }

        [HttpGet]
        public IActionResult GetAmortization(Loan model, string contractDate = null)
        {
            if (!string.IsNullOrEmpty(contractDate)) model.CreateAt = contractDate.ToDateTime();
            
            return PartialView("_GetAmortizationPartial", _service.LoanService.GetAmortization(model));
        }


        [HttpGet]
        public async Task<IActionResult> Reclosing(Guid id, State stateDeb = State.All)
        {

            ViewBag.Selected = stateDeb;
            ViewBag.Action = nameof(GetById);
            var result = await _service.LoanService.GetByIdWithRelationships(id, stateDeb);
            if (result == null) new NotFoundView();
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Reclosing(Loan model)
        {
            model.Id = Guid.Empty;
            model.UserId = GetUserLoggedId();
            model.InitialCapital = model.ActualCapital + model.ReclosingAmount;
            var clients = await _service.ClientUserService.GetAllWithRelationships(GetUserLoggedId(), null);
            ViewBag.Clients = clients.Select(x => new SelectListItem
            {
                Text = x.User.FullName,
                Value = x.Id.ToString(),
                Group = new SelectListGroup { Name = x.Enterprise.Name }
            });
            if (!ModelState.IsValid) return View(model);

            var result = await _service.LoanService.Add(model);
            if (!result)
            {

                BasicNotification("Lo sentimos, Intente de nuevo", NotificationType.error);
                return View(model);

            }

            result = await _service.LoanService.AddReclosing(model);
            if (!result)
            {
                BasicNotification("Lo sentimos, Intente de nuevo", NotificationType.error);
                return View(model);
            }
            BasicNotification("Reenganchado correctamente", NotificationType.success);

            return RedirectToAction(nameof(Index));
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> GetReclosingHistory(Guid id)
        {
            ViewBag.reclosingId = id;
            return PartialView("_GetReclosingHistoryPartial", await _service.LoanService.GetReclosing(id));
        }



        [HttpGet]
        public IActionResult GetAmortizationReclosing(Loan model)
        {
            model.ActualCapital += model.ReclosingAmount;
            return PartialView("_GetAmortizationPartial", _service.LoanService.GetAmortization(model));
        }

        [HttpGet]
        public async Task<IActionResult> OverdueInstallments() => PartialView("_OverdueInstallmentsPartial", await _service.LoanService.GetPaymentPendingClients(GetUserLoggedId()));

        [HttpGet]
        public async Task<IActionResult> GetLoanByMonth() => Ok(await _service.LoanService.GetLoanByMonth(GetUserLoggedId()));
    }
}

ERP-SPARTAN/Controllers/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinesLogic.Interfaces;
using BusinesLogic.UnitOfWork;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.Enums;

namespace ERP_SPARTAN.Controllers
{
    [Authorize(Roles = nameof(RolsAuthorization.Admin))]
    public class RolController : BaseController
    {
        private readonly IUnitOfWork _roleService;
        public RolController(IUnitOfWork roleService) => _roleService = roleService;
        public async Task<IActionResult> Index() => View(await _roleService.RoleService.GetAll());

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!string.IsNullOrEmpty(model.Name))
            {
                if(await _roleService.RoleService.Create(model.Name)) return RedirectToAction(nameof(Index));
                return View(model);
            }
            return View(model);
        }
    }
}

ERP-SPARTAN/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound";
}

<h1>NotFound</h1>

ERP-SPARTAN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HiSolutions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin.css" rel="stylesheet">
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />
    <link href="~/lib/stacktable.js/stacktable.css" rel="stylesheet" />
    <link href="~/vendor/datatables/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="~/vendor/datatables/rowreorder/rowReorder.dataTables.min.css" rel="stylesheet" />
    <link href="~/vendor/datatables/rowreorder/responsive.dataTables.min.css" rel="stylesheet" />
    <!-- Scripts--->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/vendor/sweetAlert/sweetalert2.all.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-mask/jquery.mask.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js" asp-append-version="true"></script>
    <script src="~/lib/stacktable.js/stacktable.js" asp-append-version="true"></script>
</head>
<body id="page-top">
    <header>
        <nav  class="navbar navbar-expand-lg ">
            <i class="fa fa-bars text-white" style="margin:20px; cursor:pointer;" onclick="showOrHideElement('nav-side')"></i><partial name="_TitlePartial" />
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                </div>
            </div>
        </nav>
    </header>

    <div id="wrapper">
        <!-- Sidebar -->
        <ul id="nav-side" class="sidebar navbar-nav ct-bg-secundary">
            <partial name="_NavItems" />
            <li class="nav-item nav-link-hovered ">
                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button type="submit" class="nav-link btn btn-link text-li text-hovered"><i class="fa fa-sign-out-alt"></i> Salir</button>
                </form>
            </li>
        </ul>
        <div id="content-wrapper">

            <div class="container-fluid">

                <main role="main" class="pb-3">
                    @RenderBody()
                </main>

            </div>
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span><a href="#">Copyright © Hisoftwarerd.com @DateTime.Now.Year</a> </span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/datatables/jquery.dataTables.js" asp-append-version="true"></script>
    <script src="~/vendor/datatables/dataTables.responsive.js" asp-append-version="true"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <!-- (Optional) Latest compiled and minified JavaScript translation files -->
    @RenderSection("Scripts", required: false)
</body>
</html>

ERP-SPARTAN/Views/Shared/_NavItems.cshtml
@using System.Security.Claims

@{
    var userRole = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Role)?.Value;
    var roles = User.Claims.Where(x => x.Type == ClaimTypes.Role).ToList();
    var alert = userRole == nameof(RolsAuthorization.Admin) ? "Index" : "MyAlerts";

}

<partial name="_LoginPartial" />

<li class="nav-item nav-link-hovered active">
    <a class="nav-link text-hovered" asp-action="Index" asp-controller="Home">
        <i class="fas fa-fw fa-tachometer-alt text-hovered"></i>
        <span class="">Inicio</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link nav-link-hovered" asp-action="@alert" asp-controller="Alert">
        <i class="fas fa-fw fa-bell"></i>
        <span>
            Alertas
            <span id="qyt-alert" style="position:initial; font-size:14px;margin:0;" class="badge badge-danger"></span>
        </span>
    </a>
</li>

@{switch (userRole)
    {
        case nameof(RolsAuthorization.Admin):

            <li class="nav-item">
                <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="ClientUser">
                    <i class="fas fa-fw fa-users"></i>
                    <span>Clientes</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-hovered " asp-action="Index" asp-controller="Rol">
                    <i class="fas fa-fw fa-user-secret"></i>
                    <span>Roles</span>
                </a>
            </li>
            break;
        case nameof(RolsAuthorization.ClientsUser):
            <li class="nav-item">
                <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="ClientUser">
                    <i class="fas fa-fw fa-users"></i>
                    <span>Clientes</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="Enterprise">
                    <i class="fas fa-fw fa-building"></i>
                    <span>Empresas</span>
                </a>
            </li>
            break;
        default:
            <div></div>
            break;
    }
    if (roles.Where(x => x.Value == nameof(RolsAuthorization.HiInventory)).Any())
    {
        <li class="nav-item">
            <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="Inventary">
                <i class="fas fa-boxes"></i>
                <span>Inventario</span>
            </a>
        </li>
    }
    if (roles.Where(x => x.Value == nameof(RolsAuthorization.HILoans)).Any())
    {
        if (userRole != nameof(RolsAuthorization.ClientsUser))
        {
            <li class="nav-item">
                <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="Enterprise">
                    <i class="fas fa-fw fa-building"></i>
                    <span>Empresas</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="ClientUser">
                    <i class="fas fa-fw fa-users"></i>
                    <span>Clientes</span>
                </a>
            </li>
        }

        <li class="nav-item">
            <a class="nav-link nav-link-hovered" asp-action="Index" asp-controller="Loan">
                <i class="fa fa-hand-holding-usd"></i>
                <span>Prestamos</span>
            </a>
        </li>
    }
}

ERP-SPARTAN/Views/Shared/_NotificationPartial.cshtml
<script>@if (TempData["notification"] != null) @Html.Raw(@TempData["notification"].ToString());</script>

ERP-SPARTAN/Views/Shared/_TitlePartial.cshtml
@{
    var title = string.Empty;
    if (User.IsInRole(nameof(RolsAuthorization.Admin))) title = "ADMINISTRACION";
    else if (User.IsInRole(nameof(RolsAuthorization.HILoans))) title = "HIPRESTAMOS";
    else if (User.IsInRole(nameof(RolsAuthorization.ClientsUser))) title = "HI CUENTAS";
    else title = string.Empty;

}

<a class="navbar-brand mr-1" asp-action="Index" asp-controller="Home">@title</a>