ERP-SPARTAN/Controllers/ClientUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BusinesLogic.Interfaces;
using BusinesLogic.UnitOfWork;
using Commons.Others;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Models.Enums;
using Models.Models;
using Models.Settings;
using Models.ViewModels.ClientUsers;
using Models.ViewModels.HiAccounting.ClientUsers;

namespace ERP_SPARTAN.Controllers
{
    [Authorize]
    public class ClientUserController : BaseController
    {
        private readonly IUnitOfWork _service;
        private readonly DefaultValue _settings;
        private readonly UserManager<User> _userManager;
        public ClientUserController(IUnitOfWork clientUserService, UserManager<User> userManager, IOptions<DefaultValue> options)
        {
            _service = clientUserService;
            _userManager = userManager;
            _settings = options.Value;
        }

        [Authorize(Roles = ControllersRol.ClientUser)]
        public async Task<IActionResult> Index(Guid? enterpriseId)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            var clients = await _service.ClientUserService.GetAllWithRelationships(userId,enterpriseId);
            var enterprises = await _service.EnterpriseService.GetList(userId);
            return View(new AllClientUsersVM { Clients = clients , Enterprises = enterprises });
        }

        [Authorize(Roles = ControllersRol.ClientUser)]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            return View(new CreateUserViewModel { Enterprises = await _service.EnterpriseService.GetList(userId) });
        }

        [Authorize(Roles = ControllersRol.ClientUser)]
        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel client)
        {
            client.Rol = (User.IsInRole(nameof(RolsAuthorization.ClientsUser)) || 
                User.IsInRole(nameof(RolsAuthorization.HILoans))) ? RolsAuthorization.Client : client.Rol;
            client.Enterprises = await _service.EnterpriseService.GetList(GetUserLoggedId());
            if (ModelState.IsValid)
            {
                var result = await _userManager.CreateAsync(new User
                {
                    Name = client.Name,
                    UserName = client.Email,
                    LastName = client.LastName,
                    Email = client.Email,
                    PhoneNumber = client.PhoneNumber
                }, _settings.Password);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByNameAsync(client.Email);
                    if (await _service.ClientUserService.Add(new ClientUser
                    {
                        UserId = user.Id,
                        CreatedBy = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value,
                        IdentificationCard = client.IdentificationCard,
                        EnterpriseId = client.EnterpriseId,
                        Address = client.Address
                    }))
                    {
                        var resultRol = await _userManager.AddToRoleAsync(user, client.Rol.ToString());
                        if (resultRol.Succeeded)
                        {
                            BasicNotification("Cliente Agregado!", NotificationType.success);
                            return RedirectToAction(nameof(Index));
                        }
                    }
                    BasicNotification("Ocurrió un error, no se pudo guardar el cliente", NotificationType.error);
                    return View(client);
                }
                else
                {
                    ModelState.AddModelError(nameof(client.Email), "Error ya existe un cliente con el correo " + client.Email);
                }
            }

            return View(client);
        }

        [Authorize(Roles = ControllersRol.ClientUser + "," + nameof(RolsAuthorization.Client))]

        [HttpGet]
        public async Task<IActionResult> GetById(Guid id)
        {
            var model = await _service.ClientUserService.GetByIdWithRelationships(id);
            if (model != null) return View(model);
            return new NotFoundView();
        }
        [Authorize(Roles = ControllersRol.ClientUser)]

        [HttpPost]
        public async Task<IActionResult> Update(ClientUser model)
        {
            if (ModelState.IsValid)
            {
                if (await _service.UserService.Update(model.User))
                {
                    if(await _service.ClientUserService.Update(model))
                    {
                        BasicNotification("Cliente actualizado", NotificationType.success);
                        return RedirectToAction(nameof(Index));
                    }
                }
                BasicNotification("Intente de nuevo, una de las causas es que ya exista alguien con este correo intente con otro",
                         NotificationType.error, "Lo sentimos no se pudo actualizar");
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(GetById), model);
        }
        [Authorize(Roles = ControllersRol.ClientUser)]

        [HttpPost]
        public async Task<IActionResult> Remove(Guid id)
        {
            var user = await _service.ClientUserService.GetById(id);
            if (user == null) return NotFound();
            if (await _service.UserService.LockAndUnlockUser(user.UserId))
            {
                if (await _service.ClientUserService.SoftRemove(id)) return Ok(true);
            }
            return BadRequest();
        }
        [Authorize(Roles = ControllersRol.ClientUser)]

        [HttpPost]
        public async Task<IActionResult> LockOrUnlockUser(string id)
        {
            if (await _service.UserService.LockAndUnlockUser(id)) return Ok(true);
            return BadRequest();
        }

        [Authorize(Roles = nameof(RolsAuthorization.Client))]
        [HttpGet]
        public async Task<IActionResult> GetMyClientAccount(string UserName)
        {
            var user = await _userManager.FindByNameAsync(UserName);
            if (user == null) return NotFound();
            var client = await _service.ClientUserService.GetClientByUserId(user.Id);
            if (client == null) return NotFound();
            return RedirectToAction(nameof(MovementController.GetByClientUser), "Movement", new { Id = client.Id });
        }

        [HttpGet]
        public async Task<PartialViewResult> GetAllOptionsClients() 
            => PartialView("_ClientOptionsPartial", await _service.ClientUserService.GetAllWithRelationships(GetUserLoggedId(), null));
        
    }
}

ERP-SPARTAN/Controllers/UserController.cs
using BusinesLogic.UnitOfWork;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Models.Enums;
using Models.Models;
using Models.Settings;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ERP_SPARTAN.Controllers
{
    [Authorize]
    public class UserController : BaseController
    {
        private readonly IUnitOfWork _service;
        private readonly UserManager<User> _userManager;
        private readonly DefaultValue _settings;
        public UserController(IUnitOfWork service, UserManager<User> userManager, IOptions<DefaultValue> option)
        {
            _service = service;
            _userManager = userManager;
            _settings = option.Value;
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            return View(await _service.UserService.GetUserAsync(userId));
        }

        [HttpPost]
        public async Task<IActionResult> Update(User model)
        {
            if (ModelState.IsValid)
            {
                if (await _service.UserService.Update(model))
                {
                    BasicNotification("Actualizado Correctamente", NotificationType.success);
                    return RedirectToAction(nameof(Profile));
                }
                BasicNotification("Ha ocurrido un error , una de las razones puede ser que exista un correo igual al ingresado intente con otro", NotificationType.error);
            }
            return View(nameof(Profile), model);
        }

        [Authorize(Roles = nameof(RolsAuthorization.Admin))]
        [HttpGet]
        public async Task<IActionResult> AddToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return new NotFoundView();
            var result = await _service.UserService.GetUserAsync(id);
            ViewBag.UserRols = await _userManager.GetRolesAsync(result);
            ViewBag.Rols = await _service.RoleService.GetListItem();
            if (result == null) return new NotFoundView();
            return View(result);
        }

        [Authorize(Roles = nameof(RolsAuthorization.Admin))]
        [HttpPost]
        public async Task<IActionResult> AddToRole(string id, string RoleId)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(RoleId)) return new NotFoundView();
            var user = await _service.UserService.GetUserAsync(id);
            if (user == null) return new NotFoundView();
            var result = await _service.UserService.AddToRole(id, RoleId);
            if (!result) BasicNotification("Intente Nuevamente", NotificationType.error, "Error");
            BasicNotification("Cliente agregado al nuevo rol, puede continuar agregando mas roles", NotificationType.success, "Listo");
            return RedirectToAction(nameof(AddToRole), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserRole(string id, string roleName)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(roleName)) return BadRequest();
            return Ok(await _service.UserService.RemoveUserRoleAsync(id, roleName));
        }

        [HttpGet]
        public async Task<IActionResult> ResetPassword(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) BasicNotification("Error el usuario no existe", NotificationType.error);
            var token = await _userManager.GeneratePasswordResetTokenAsync(user);
            var result = await _userManager.ResetPasswordAsync(user, token, _settings.Password);
            BasicNotification("Contraseña restablecida", NotificationType.success);
            return RedirectToAction(nameof(Index), nameof(ClientUser));
        }
    }
}

ERP-SPARTAN/Views/User/AddToRole.cshtml
@model User
@{
    ViewData["Title"] = "AddToRole";
}



<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col">
                <h1>Cambio de roles para el usuario @Model.FullName</h1>
                Correo: <span class="text-muted">@Model.UserName</span>
            </div>
        </div>
    </div>
</div>
<hr />

<div class="row ">

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div class="card">
            <div class="card-body">
                <h2 class="text-center">Roles del Usuario</h2>
                <ul class="list-group">
                    @foreach (var item in ViewBag.UserRols)
                    {
                        <li class="list-group-item">
                            @item <span class="ml-5 text-muted" style="cursor:pointer;" onclick="ShowSweetConfirmRemoveRoleDialog('@Model.Id','@item','/User','RemoveUserRole')">Remover</span>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
        <div class="card">
            <div class="card-body">
                <h2 class="text-center">Nuevo Rol</h2>
                <form asp-action="AddToRole">
                    <input asp-for="Id" type="hidden" />
                    <div class="form-group">
                        <select class="form-control" name="RoleId" asp-items="ViewBag.Rols"></select>
                        <button class="btn btn-success btn-block mt-2">Agregar</button>
                        <a asp-action="Index" asp-controller="ClientUser" class="btn btn-dark btn-block mt-2">Volver</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

</div>
<script src="~/js/Shared/httpRequest.js" asp-append-version="true"></script>
<partial name="_NotificationPartial" />

ERP-SPARTAN/Views/User/Profile.cshtml
@model User
@inject IOptions<Models.Settings.DefaultValue> options

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col">
                <div class="row justify-content-center">
                    <div class="col-sm-12 text-center">
                        <img style="border-radius:50px;" src="@options.Value.Avatar@Model.UserName&size=200" alt="@Model.UserName .png" class="img-thumbnail text-center">
                        <p class="font-weight-light">@Model.FullName <br />Creado el : @Model.CreateAt.ToShortDateString()</p>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <form class="form-group" asp-controller="User" asp-action="Update" method="post">
                            <div asp-validation-summary="All"></div>
                            <input asp-for="UserName" type="hidden" />
                            <input asp-for="Id" type="hidden" />
                            <input asp-for="CreateAt" type="hidden" />

                            <div class="form-group">
                                <label asp-for="Name">Nombre</label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LastName">Apellidos</label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PhoneNumber">Numero</label>
                                <input asp-for="PhoneNumber" id="phoneNumber" class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Email">Correo</label>
                                <input asp-for="Email" disabled class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary">Editar</button>
                                <a asp-action="Index" asp-controller="Home" class="btn btn-dark">Cancelar</a>
                                <a href="/Identity/Account/Manage/ChangePassword" class="btn btn-dark">Cambiar contraseña</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<partial name="_NotificationPartial" />