ERP-SPARTAN/Controllers/EnterpriseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BusinesLogic.UnitOfWork;
using Commons.Others;
using ERP_SPARTAN.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Models.Enums;
using Models.Models.Accounting;

namespace ERP_SPARTAN.Controllers
{
    [Authorize(Roles = ControllersRol.EnterPrise)]
    public class EnterpriseController : BaseController
    {
        private readonly IUnitOfWork _services;
        public EnterpriseController(IUnitOfWork services) => _services = services;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            return View(await _services.EnterpriseService.GetList(userId));
        }

        [HttpGet]
        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(Enterprise model)
        {
            var userId = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value;
            model.UserId = userId;
            if (!ModelState.IsValid) return View(model);
            var result = await _services.EnterpriseService.Add(model);
            if (!result)
            {
                BasicNotification("Ocurrio un error intente de nuevo", NotificationType.error, "Lo sentimos");
                return View(model);
            }
            BasicNotification("Agregado correctamente", NotificationType.success, "Exito");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var result = await _services.EnterpriseService.GetById(id);
            if (result == null) return new NotFoundView();
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Enterprise model)
        {
            if (!ModelState.IsValid) return View(model);
            var result = await _services.EnterpriseService.Update(model);
            if (!result)
            {
                BasicNotification("Ocurrio un error intente de nuevo", NotificationType.error, "Lo sentimos intente de nuevo");
                return View(model);
            }
            BasicNotification("Actualizado", NotificationType.success, "Exito");
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Remove(Guid id)
        {
            var enterprise = await _services.EnterpriseService.GetById(id);
            if (enterprise == null) return new NotFoundView();
            return View(enterprise);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var enterprise = await _services.EnterpriseService.GetById(id);
            if (enterprise == null) return new NotFoundView();
            var result = await _services.EnterpriseService.Remove(enterprise);
            if (!result)
            {
                BasicNotification("Lo sentimos, intente de nuevo", NotificationType.error, "Lo sentimos");
                return View(nameof(Remove), enterprise);
            }
            BasicNotification("Eliminado con exito", NotificationType.success, "Eliminado");
            return RedirectToAction(nameof(Index));
        }
    }
}

ERP-SPARTAN/Views/Enterprise/Create.cshtml
@model Models.Models.Accounting.Enterprise

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-body">
        <h1>Nueva</h1>
        <h4>Empresa</h4>
    </div>
</div>

<hr />

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" id="phoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <textarea asp-for="Address" class="form-control"></textarea>
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Crear" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-dark">Volver</a>
                    </div>
                </form>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <img src="~/img/svg/newenterprise.svg" width="500" />
            </div>
        </div>

    </div>
</div>

ERP-SPARTAN/Views/Enterprise/Index.cshtml
@model IEnumerable<Models.Models.Accounting.Enterprise>

@{
    ViewData["Title"] = "Index";
}



<div class="card">
    <div class="card-body">
        <div class="container-fluid">

            <div class="row justify-content-between">
                <div class="col-xs-11 ">

                    <h1><i class="fas fa-fw fa-building"></i> Empresas</h1>
                </div>
                <div class="col-xs-1">
                    <a asp-action="Create" asp-controller="Enterprise" class="btn ct-bg-primary text-white">Nuevo</a>
                </div>
                <div class="col-12">
                </div>
            </div>

        </div>
    </div>
</div>

<hr />


<div class="card">
    <div class="card-body">

        <div class=" mb-3 p-1" style="width:100%">
            <table class="table data-table display nowrap" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PhoneNumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>
                        <th>
                            Creación
                        </th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                                <i class="ml-5 col-smd d-inline d-sm-inline d-md-inline d-lg-none text-danger " style="font-weight:bold">(pulsame para ver mas información)</i>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Address)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedAtStr)
                            </td>
                            <td>
                                <a asp-action="Update" class="btn btn-sm btn-warning text-white" asp-route-id="@item.Id"><i class="fa fa-edit"></i></a>
                                <a asp-action="Remove" class="btn btn-sm btn-danger text-white" asp-route-id="@item.Id"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>

    </div>
</div>


<partial name="_NotificationPartial" />

ERP-SPARTAN/Views/Enterprise/Remove.cshtml
@model Models.Models.Accounting.Enterprise

@{
    ViewData["Title"] = "Remove";
}

<h1>Eliminar @Model.Name</h1>
<h3>Seguro que desea eliminarla , si lo elimina los clientes que tiene esta empresa tambien seran eliminados</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-dark">Volver</a>
    </form>
</div>

ERP-SPARTAN/Views/Enterprise/Update.cshtml
@model Models.Models.Accounting.Enterprise

@{
    ViewData["Title"] = "Update";
}


<div class="card">
    <div class="card-body">
        <h1>Actualizar</h1>
        <h4>Empresa @Model.Name</h4>
    </div>
</div>
<hr />

<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <form asp-action="Update">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" id="phoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="UserId" />
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <input type="submit" value="Actualizar" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-dark">Volver</a>
                    </div>
                </form>
            </div>
            <div class="col-12 col-sm-12 col-md-6">
                <img src="~/img/svg/newenterprise.svg" width="500" />
            </div>
        </div>
    </div>
</div>


<partial name="_NotificationPartial" />